# https://github.com/KaiHotz/react-rollup-boilerplate

def auto_assets
  system "rm ./app/assets/auto-*"

  for folder in Dir.folders('./app/assets/auto')
    info = ["Auto asset compiler: #{folder}"]
    # JS FILES
    js_files = get_files folder, :js
    data = []
    for file in js_files
      if file.start_with?('/* ')
        data.push file
      else
        ext = file.split('.').last.to_sym
        if ext == :svelte
          name = file.split('/').last.split('.').first.gsub('-', '_')
          data.push <<~DATA
            import Svelte_#{name} from '#{file}';
            Svelte.bind('s-#{name.gsub('_', '-')}', Svelte_#{name});
          DATA
            .chomp
        elsif [:js, :coffee, :fez].include?(ext)
          data.push %[import "#{file}";]
        else
          raise "Unknown extension on #{file}"
        end
      end
    end

    if data[0]
      file = "./app/assets/auto-#{folder}.js"
      info.push file
      File.write(file, data.join("\n\n"))
    end

    # CSS files — wrapped in @layer base so Tailwind v4 utilities can override
    css_files = get_files folder, :css
    data = []
    for file in css_files
      if file.start_with?('/* ')
        data.push file
      else
        data.push %[  @include meta.load-css("#{file}");]
      end
    end

    if data[0]
      css = <<~DATA
        /* DO NOT EDIT - auto generated by assets:auto - edit source at ./app/assets/auto/#{folder}/css */

        @use "sass:meta";

        @layer base {
        #{data.join("\n")}
        }
      DATA
      file = "./app/assets/auto-#{folder}.scss"
      info.push file
      File.write(file, css)
    end

    Lux.info info.join(' - ')
  end
end

def get_files folder, ext
  root = "./app/assets/auto/#{folder}/#{ext}"
  return [] unless Dir.exist?(root)
  files = Dir.find(root)
  files = files.reject { _1.include?('/!') }

  last_file = Dir.files(root).select { _1.include?('!last') }.first
  files.push "#{root}/#{last_file}" if last_file

  files = files.map do |f|
    if f =~ /\.rb$/
      data = instance_eval File.read f
      "/* #{f} */\n#{data}"
    else
      f
    end
  end

  files = files.map { _1.sub('./app/assets/', './') }

  files
end

###

namespace :assets do
  desc 'Auto assets compiler (app/assets/auto)'
  task :auto do
    auto_assets
  end
end
