# web_common asset pipeline. Loaded only for apps that list the plugin.
#
#   lux assets:generate - app/assets/<name>.<ext>.rb -> <name>.tmp.<ext>
#   lux assets:build   - generate, assets:compile (app contract), favicon,
#                        then write public/manifest.json
#   lux assets:deploy  - build -> assets:upload per manifest entry
#
# assets:compile and assets:upload are app contracts (bin/cli/assets_hammer.rb);
# deploy only uploads when production sets cdn_root, otherwise `lux pack` ships
# public/assets and they are served from /assets.
#
# Generators: `app/assets/<name>.<ext>.rb` (any Lux::Root, so plugin mounts can
# ship one) is evaluated with the app loaded; the returned string is written to
# `app/assets/<name>.tmp.<ext>` in the app tree (gitignored via *.tmp.*), where
# the app's bundle imports it.

require 'fileutils'

module LuxAssets
  module_function

  def generate
    Lux.root.files('app/assets/*.*.rb').each do |rb_path|
      base     = rb_path.to_s.delete_suffix('.rb')
      file_ext = File.extname(base)
      out_path = Lux.root.join("app/assets/#{File.basename(base, file_ext)}.tmp#{file_ext}")

      body = instance_eval(File.read(rb_path), rb_path.to_s).to_s
      # a plugin mount source keeps its absolute path, so the banner points at the real file
      source = rb_path.to_s.start_with?("#{Lux.root}/") ? Lux.root.pretty(rb_path) : rb_path.to_s
      FileUtils.mkdir_p(out_path.dirname)
      out_path.write("#{banner_for(file_ext, source)}\n#{body}\n")

      Lux.shell.info "  gen #{Lux.root.pretty(out_path)} <- #{Lux.root.pretty(rb_path)}"
    end
  end

  def banner_for ext, rb_path
    ext == '.js' ? "// autogenerated from #{rb_path} - do not edit" : "/* autogenerated from #{rb_path} - do not edit */"
  end
end

namespace :assets do
  task :generate do
    desc 'Run app/assets/<name>.<ext>.rb generators into <name>.tmp.<ext> (dev watchers call it before rollup -cw)'
    needs :app
    proc do |_opts|
      LuxAssets.generate
    end
  end

  task :build do
    desc 'Generate app/assets/*.tmp.*, run assets:compile (app), build favicon, write public/manifest.json'
    needs :app
    proc do |_opts|
      LuxAssets.generate
      hammer 'assets:compile'

      # the app compile may empty public/assets, so the touch icon goes in
      # after it and before the manifest fingerprints it
      Favicon.build! if defined?(Favicon) && File.exist?(Favicon::SOURCE)

      next Lux.shell.info('assets:build - nothing to build') unless Dir.exist?('./public/assets')

      CdnAsset.write_manifest
    end
  end

  task :deploy do
    desc 'Full asset pipeline: build -> assets:upload per file when cdn_root is set'
    needs :app
    proc do |_opts|
      hammer 'assets:build'

      if (root = Lux.config.dig('production', 'cdn_root')).present?
        CdnAsset.uploads.each do |local, remote|
          hammer 'assets:upload', local, remote
          puts "* #{local} -> #{root}/#{remote}"
        end
      end
    end
  end
end
