require 'test_helper'
require_relative '../loader'

describe 'dev' do
  it 'expects to capture error' do
    $no_error_print = true
    response = GenericApi.render :about
    $no_error_print = false
    _(response).must_equal({:error=>{:messages=>["Error happens"]}, :meta=>{:ip=>"1.2.3.4"}, :status=>500, :success=>false})
  end

  it 'gets error generated by code' do
    response = GenericApi.render :get_money
    _(response).must_equal({:error=>{:messages=>["$ not found", "405"]}, :meta=>{:ip=>"1.2.3.4"}, :status=>400, :success=>false})
  end

  it 'can generete error in root' do
    err = GenericApi.response_error('foo bar').to_h
    _(err[:error][:messages][0]).must_equal 'foo bar'
  end
end
